# brew tap
tap 'homebrew/cask'
# set arguments for all 'brew cask install' commands
cask_args appdir: '~/Applications'

# brew install
brew 'mas'
brew 'python'
brew 'precommit'
brew 'nvm'
brew 'go'

# brew cask install
cask 'aerial'
cask 'alfred'
cask 'firefox'
cask 'figma'
cask 'github'
cask 'goland'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'notion'
cask 'postman'
cask 'skitch'
cask 'slack'
cask 'textmate'
cask 'vagrant'
cask 'visual-studio-code'

# brew mas install
mas 'Xcode', id: 497799835
mas 'iAWriter', id: 775737590
mas 'Lungo', id: 1263070803
